spring:
  application:
    name: lovable-clone

  datasource:
    url: jdbc:postgresql://localhost:9000/testDB
    username: testUser
    # Replaced hardcoded password with an environment variable
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
jwt:
  # Replaced hardcoded key with an environment variable
  secret-key: ${JWT_SECRET_KEY}

stripe:
  api:
    # Replaced hardcoded Stripe API key
    secret: ${STRIPE_API_KEY}
  webhook:
    # Replaced hardcoded Stripe Webhook secret
    secret: ${STRIPE_WEBHOOK_SECRET}

client.url: http://localhost:8080
