-- Baseline schema for lovable-clone.
-- Mirrors the schema Hibernate (ddl-auto: update) created from the JPA entities as of this migration.
-- Existing databases are baselined past this file (spring.flyway.baseline-on-migrate: true);
-- fresh databases execute it. Never edit this file once applied anywhere — fix forward with V2+.

create table users (
    id bigint generated by default as identity primary key,
    username varchar(255),
    password varchar(255),
    name varchar(255),
    stripe_customer_id varchar(255) unique,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    deleted_at timestamp(6) with time zone
);

create table projects (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    description text,
    is_public boolean,
    owner_id bigint not null references users (id),
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    deleted_at timestamp(6) with time zone
);

create index idx_projects_updated_at_desc on projects (updated_at desc, deleted_at);
create index idx_projects_deleted_at_updated_at_desc on projects (deleted_at, updated_at desc);
create index idx_project_deleted_at on projects (deleted_at);

create table project_files (
    id bigint generated by default as identity primary key,
    project_id bigint not null references projects (id),
    path varchar(255) not null,
    minio_object_key varchar(255),
    content text,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone
);

create table chat_sessions (
    project_id bigint not null references projects (id),
    user_id bigint not null references users (id),
    title varchar(255),
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone,
    deleted_at timestamp(6) with time zone,
    primary key (project_id, user_id)
);

create table chat_messages (
    id bigint generated by default as identity primary key,
    project_id bigint not null,
    user_id bigint not null,
    content text not null,
    role varchar(255) not null check (role in ('USER', 'ASSISTANT', 'SYSTEM', 'TOOL')),
    tokens_used integer,
    created_at timestamp(6) with time zone not null,
    foreign key (project_id, user_id) references chat_sessions (project_id, user_id)
);

create table chat_events (
    id bigint generated by default as identity primary key,
    chat_message_id bigint not null references chat_messages (id),
    type varchar(255) not null check (type in ('THOUGHT', 'MESSAGE', 'FILE_EDIT', 'TOOL_LOG')),
    sequence_order integer not null,
    content text,
    file_path varchar(255),
    metadata text
);

create table plan (
    id bigint generated by default as identity primary key,
    name varchar(255),
    stripe_price_id varchar(255) unique,
    max_projects integer,
    max_tokens_per_day integer,
    max_previews integer,
    unlimited_ai boolean,
    active boolean
);

create table subscription (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users (id),
    plan_id bigint not null references plan (id),
    status varchar(255) check (status in ('ACTIVE', 'TRAILING', 'CANCELLED', 'PAST_DUE', 'INCOMPLETE')),
    stripe_subscription_id varchar(255),
    current_period_start timestamp(6) with time zone,
    current_period_end timestamp(6) with time zone,
    cancel_at_period_end boolean,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone
);

create table usage_logs (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users (id),
    project_id bigint references projects (id),
    action varchar(255),
    tokens_user integer,
    duration_ms integer,
    meta_data text,
    date date not null,
    created_at timestamp(6) with time zone not null
);

create table project_members (
    project_id bigint not null references projects (id),
    user_id bigint not null references users (id),
    project_role varchar(255) not null check (project_role in ('EDITOR', 'VIEWER', 'OWNER')),
    invited_at timestamp(6) with time zone,
    accepted_at timestamp(6) with time zone,
    primary key (project_id, user_id)
);
